name: ci
on: [push, pull_request]
jobs:
  build-unix:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven Repo
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-node
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Build with Maven
      run: ./mvnw -B package -DskipTests --file pom.xml